name: ebaybaymo
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  stacked: ^3.4.0
  stacked_services: ^1.1.0
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  image_picker: ^1.1.2

dev_dependencies:
  build_runner: ^2.4.5
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  mockito: ^5.4.1
  stacked_generator: ^1.3.3
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.2.5

flutter_launcher_icons:
   android: "opc"
   ios: true
   image_path: "lib/resources/images/logo_ebaybaymo.png"

flutter_native_splash:
  color: "#A52A2A" # Brown color as preferred
  image: lib/resources/images/logo.png
  android: true
  ios: true
  web: false

android_12:
  image:lib/resources/images/logo.png

flutter:
  uses-material-design: true

  assets:
    - lib/resources/images/
